title: Bruna Zamith
url: "https://bzamith.github.io/"
baseurl: ""

markdown: kramdown

tracking_id: #

footer: yes
footer_url: "https://github.com/ankitsultana"
footer_text: "Page design by Ankit Sultana"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "Home"
   link: "https://bzamith.github.io/"
 - name: "Studies"
   link: "studies"
 - name: "Concepts"
   link: "concepts"
