title: Bruna Zamith
logo: /assets/img/femalecodertocat.png
description: Computer Engineering Student at Federal University of Sao Carlos. Interested in and currently working with Data Science and Software Engineering.
show_downloads: true
google_analytics: true
theme: jekyll-theme-minimal
