title: B.Z. Portifolio
logo: /assets/img/logo.jpeg
description: Computer Engineering Student at Federal University of Sao Carlos. Interested in and currently working with Data Science, Machine Learning and Bioinformatics.
show_downloads: true
theme: jekyll-theme-minimal
